"""init table

Revision ID: 0001
Revises:
Create Date: 2025-05-22 19:22:22.184057

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("subversion", sa.Integer(), nullable=False),
        sa.Column("train_ratio", sa.Float(), nullable=False),
        sa.Column("validation_ratio", sa.Float(), nullable=False),
        sa.Column("test_ratio", sa.Float(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hyperparameter_type",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("param_name", sa.String(length=500), nullable=False),
        sa.Column("param_type", sa.String(length=100), nullable=False),
        sa.Column("default_value", sa.String(length=500), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "inference_image_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_uri", sa.String(length=4000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_format",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_provider",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_param_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("param_name", sa.String(length=500), nullable=False),
        sa.Column("param_type", sa.String(length=100), nullable=False),
        sa.Column("default_value", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "train_image_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("image_uri", sa.String(length=4000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artifact_path", sa.String(length=4000), nullable=False),
        sa.Column("uri", sa.String(length=4000), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["dataset_id"], ["dataset.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("type_id", sa.Integer(), nullable=False),
        sa.Column("format_id", sa.Integer(), nullable=False),
        sa.Column("parent_model_id", sa.Integer(), nullable=False),
        sa.Column("learning_enable_yn", sa.Boolean(), nullable=False),
        sa.Column("train_image_registry_id", sa.Integer(), nullable=False),
        sa.Column("inference_image_registry_id", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("subversion", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["format_id"],
            ["model_format.id"],
        ),
        sa.ForeignKeyConstraint(
            ["inference_image_registry_id"],
            ["inference_image_registry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_model_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["model_provider.id"],
        ),
        sa.ForeignKeyConstraint(
            ["train_image_registry_id"],
            ["train_image_registry.id"],
        ),
        sa.ForeignKeyConstraint(
            ["type_id"],
            ["model_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "experiment",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("reference_model_id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("kubeflow_run_id", sa.String(length=500), nullable=False),
        sa.Column("mlflow_run_id", sa.String(length=500), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("learning_yn", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "hyperparameter",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=500), nullable=False),
        sa.Column("reference_model_id", sa.Integer(), nullable=False),
        sa.Column("hyperparameter_type_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["hyperparameter_type_id"],
            ["hyperparameter_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["reference_model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "model_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("artifact_path", sa.String(length=4000), nullable=False),
        sa.Column("uri", sa.String(length=4000), nullable=False),
        sa.Column("reference_model_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(["reference_model_id"], ["model.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "service_endpoint",
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("url", sa.String(length=4000), nullable=False),
        sa.Column("service_param_type_id", sa.Integer(), nullable=False),
        sa.Column("service_param_value", sa.String(length=500), nullable=False),
        sa.Column("reference_model_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["reference_model_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_param_type_id"],
            ["service_param_type.id"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("service_endpoint")
    op.drop_table("model_registry")
    op.drop_table("hyperparameter")
    op.drop_table("experiment")
    op.drop_table("model")
    op.drop_table("dataset_registry")
    op.drop_table("user")
    op.drop_table("train_image_registry")
    op.drop_table("service_param_type")
    op.drop_table("model_type")
    op.drop_table("model_provider")
    op.drop_table("model_format")
    op.drop_table("inference_image_registry")
    op.drop_table("hyperparameter_type")
    op.drop_table("dataset")
    # ### end Alembic commands ###
