"""hyperparameter fk change

Revision ID: 0002
Revises: 0001
Create Date: 2025-07-04 16:00:38.646335

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("hyperparameter", sa.Column("experiment_id", sa.BigInteger(), nullable=False))
    op.drop_constraint("hyperparameter_ibfk_2", "hyperparameter", type_="foreignkey")
    op.create_foreign_key(None, "hyperparameter", "experiment", ["experiment_id"], ["id"])
    op.drop_column("hyperparameter", "reference_model_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "hyperparameter",
        sa.Column("reference_model_id", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "hyperparameter", type_="foreignkey")
    op.create_foreign_key("hyperparameter_ibfk_2", "hyperparameter", "model", ["reference_model_id"], ["id"])
    op.drop_column("hyperparameter", "experiment_id")
    # ### end Alembic commands ###
