"""model table fixing

Revision ID: 0003
Revises: 0002
Create Date: 2025-07-15 18:04:21.912937

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: Union[str, None] = "0002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model", "parent_model_id", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model", "parent_model_id", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # ### end Alembic commands ###
