"""model table nullabe fix

Revision ID: 0004
Revises: 0003
Create Date: 2025-07-15 18:10:33.439487

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: Union[str, None] = "0003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("model", "train_image_registry_id", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column(
        "model", "inference_image_registry_id", existing_type=mysql.INTEGER(display_width=11), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model", "inference_image_registry_id", existing_type=mysql.INTEGER(display_width=11), nullable=False
    )
    op.alter_column("model", "train_image_registry_id", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    # ### end Alembic commands ###
