"""add workflow component column

Revision ID: 0018
Revises: 0017
Create Date: 2025-11-18 09:41:33.841453

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0018"
down_revision: Union[str, None] = "0017"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_components", sa.Column("knowledge_base_id", sa.Integer(), nullable=True))
    op.add_column("workflow_components", sa.Column("prompt_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "workflow_components", "prompt", ["prompt_id"], ["id"])
    op.create_foreign_key(None, "workflow_components", "knowledge_base", ["knowledge_base_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workflow_components", type_="foreignkey")
    op.drop_constraint(None, "workflow_components", type_="foreignkey")
    op.drop_column("workflow_components", "prompt_id")
    op.drop_column("workflow_components", "knowledge_base_id")
    # ### end Alembic commands ###
