"""upgrade kserve deployments

Revision ID: 0029
Revises: 0028
Create Date: 2026-04-22 10:08:36.553919

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0029"
down_revision: Union[str, None] = "0028"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_workflow_deployments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("workflow_id", sa.String(length=36), nullable=False),
        sa.Column("component_id", sa.String(length=255), nullable=False),
        sa.Column("service_name", sa.String(length=255), nullable=False),
        sa.Column("service_hostname", sa.String(length=500), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("internal_url", sa.String(length=500), nullable=True),
        sa.Column(
            "deployment_type",
            sa.Enum("KSERVE", "OLLAMA", "REMOTE", name="workflowservingdeploymenttype"),
            nullable=False,
        ),
        sa.Column("pvc", sa.String(length=255), nullable=True),
        sa.Column("device_type", sa.Enum("GPU", "CPU", name="servingdevicetype"), nullable=True),
        sa.Column("remote_api_url", sa.String(length=500), nullable=True),
        sa.Column(
            "status", sa.Enum("DEPLOYING", "DEPLOYED", "FAILED", "DELETED", name="deploymentstatus"), nullable=False
        ),
        sa.Column("deployed_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("error_message", sa.String(length=1000), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.Column("deleted_by", sa.String(length=40), nullable=True),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflows.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("service_name"),
    )
    op.create_index(
        "ix_model_workflow_deployments_component_id", "model_workflow_deployments", ["component_id"], unique=False
    )
    op.create_index(
        "ix_model_workflow_deployments_service_name", "model_workflow_deployments", ["service_name"], unique=False
    )
    op.create_index("ix_model_workflow_deployments_status", "model_workflow_deployments", ["status"], unique=False)
    op.create_index(
        "ix_model_workflow_deployments_workflow_id", "model_workflow_deployments", ["workflow_id"], unique=False
    )
    op.drop_table("kserve_deployments")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kserve_deployments",
        sa.Column("id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("workflow_id", mysql.VARCHAR(length=36), nullable=False),
        sa.Column("component_id", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("service_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("service_hostname", mysql.VARCHAR(length=500), nullable=False),
        sa.Column("model_name", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("internal_url", mysql.VARCHAR(length=500), nullable=True),
        sa.Column(
            "status",
            mysql.ENUM("DEPLOYING", "DEPLOYED", "FAILED", "DELETED"),
            server_default=sa.text("'DEPLOYING'"),
            nullable=False,
        ),
        sa.Column("deployed_at", mysql.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", mysql.TIMESTAMP(), nullable=True),
        sa.Column("error_message", mysql.VARCHAR(length=1000), nullable=True),
        sa.Column("created_at", mysql.TIMESTAMP(), server_default=sa.text("current_timestamp()"), nullable=False),
        sa.Column("created_by", mysql.VARCHAR(length=40), server_default=sa.text("''"), nullable=True),
        sa.Column(
            "updated_at",
            mysql.TIMESTAMP(),
            server_default=sa.text("current_timestamp() ON UPDATE current_timestamp()"),
            nullable=True,
        ),
        sa.Column("updated_by", mysql.VARCHAR(length=40), server_default=sa.text("''"), nullable=True),
        sa.Column("deleted_by", mysql.VARCHAR(length=40), server_default=sa.text("''"), nullable=True),
        sa.ForeignKeyConstraint(["workflow_id"], ["workflows.id"], name="kserve_deployments_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_general_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_index("service_name", "kserve_deployments", ["service_name"], unique=True)
    op.create_index("ix_kserve_deployments_workflow_id", "kserve_deployments", ["workflow_id"], unique=False)
    op.create_index("ix_kserve_deployments_status", "kserve_deployments", ["status"], unique=False)
    op.create_index("ix_kserve_deployments_service_name", "kserve_deployments", ["service_name"], unique=False)
    op.create_index("ix_kserve_deployments_component_id", "kserve_deployments", ["component_id"], unique=False)
    op.drop_table("model_workflow_deployments")
    # ### end Alembic commands ###
