"""add serving node to mwd table

Revision ID: 0030
Revises: 0029
Create Date: 2026-04-22 16:19:00.239141

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0030"
down_revision: Union[str, None] = "0029"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("model_workflow_deployments", sa.Column("serving_node_name", sa.String(length=253), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_workflow_deployments", "serving_node_name")
    # ### end Alembic commands ###
