"""model improvements table

Revision ID: 0031
Revises: 0030
Create Date: 2026-04-28 13:01:11.489793

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0031"
down_revision: Union[str, None] = "0030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_improvement_task",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("source_model_id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("created_by_username", sa.String(length=100), nullable=False),
        sa.Column("last_known_status", sa.String(length=20), nullable=False),
        sa.Column("result_model_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["result_model_id"],
            ["model.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_model_id"],
            ["model.id"],
        ),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_model_improvement_task_source_model_id"), "model_improvement_task", ["source_model_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("model_improvement_task")
    # ### end Alembic commands ###
