"""model improvements table cascade delete

Revision ID: 0032
Revises: 0031
Create Date: 2026-04-28 14:41:53.851582

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0032"
down_revision: Union[str, None] = "0031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("model_improvement_task_ibfk_2", "model_improvement_task", type_="foreignkey")
    op.drop_constraint("model_improvement_task_ibfk_1", "model_improvement_task", type_="foreignkey")
    op.create_foreign_key(None, "model_improvement_task", "model", ["source_model_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "model_improvement_task", "model", ["result_model_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "model_improvement_task", type_="foreignkey")
    op.drop_constraint(None, "model_improvement_task", type_="foreignkey")
    op.create_foreign_key(
        "model_improvement_task_ibfk_1", "model_improvement_task", "model", ["result_model_id"], ["id"]
    )
    op.create_foreign_key(
        "model_improvement_task_ibfk_2", "model_improvement_task", "model", ["source_model_id"], ["id"]
    )
    # ### end Alembic commands ###
