"""add xy to workflow component

Revision ID: 0033
Revises: 0032
Create Date: 2026-05-13 15:01:57.570236

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0033"
down_revision: Union[str, None] = "0032"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("workflow_components", sa.Column("x", sa.Integer(), nullable=True))
    op.add_column("workflow_components", sa.Column("y", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workflow_components", "y")
    op.drop_column("workflow_components", "x")
    # ### end Alembic commands ###
