"""normalize service_monitoring add user_id success drop constant metric columns

Revision ID: 0034
Revises: 0033
Create Date: 2026-05-22 10:36:48.964093

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0034"
down_revision: Union[str, None] = "0033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 신규 컬럼 (success 는 백필 후 NOT NULL 로 전환)
    op.add_column("service_monitoring", sa.Column("user_id", sa.BigInteger(), nullable=True))
    op.add_column("service_monitoring", sa.Column("success", sa.Boolean(), nullable=True))

    # 기존 데이터 백필: error_count == 0 이면 성공 (error_count drop 전에 수행)
    op.execute("UPDATE service_monitoring SET success = (error_count = 0)")
    op.alter_column(
        "service_monitoring", "success", existing_type=sa.Boolean(), nullable=False, server_default=sa.true()
    )

    # token_usage NOT NULL (기존 값은 0 이므로 안전)
    op.alter_column(
        "service_monitoring",
        "token_usage",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
        existing_server_default=sa.text("0"),
    )

    op.create_index(
        "ix_service_monitoring_service_id_timestamp", "service_monitoring", ["service_id", "timestamp"], unique=False
    )
    op.create_foreign_key("fk_service_monitoring_user_id", "service_monitoring", "user", ["user_id"], ["id"])

    # 상수 컬럼 제거 (백필 이후)
    op.drop_column("service_monitoring", "active_users")
    op.drop_column("service_monitoring", "error_count")
    op.drop_column("service_monitoring", "success_rate")
    op.drop_column("service_monitoring", "message_count")
    op.drop_column("service_monitoring", "avg_interaction_count")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "service_monitoring",
        sa.Column("avg_interaction_count", mysql.FLOAT(), server_default=sa.text("0"), nullable=True),
    )
    op.add_column(
        "service_monitoring",
        sa.Column(
            "message_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "service_monitoring", sa.Column("success_rate", mysql.FLOAT(), server_default=sa.text("100"), nullable=True)
    )
    op.add_column(
        "service_monitoring",
        sa.Column(
            "error_count",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "service_monitoring",
        sa.Column(
            "active_users",
            mysql.INTEGER(display_width=11),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint("fk_service_monitoring_user_id", "service_monitoring", type_="foreignkey")
    op.drop_index("ix_service_monitoring_service_id_timestamp", table_name="service_monitoring")
    op.alter_column(
        "service_monitoring",
        "token_usage",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.drop_column("service_monitoring", "success")
    op.drop_column("service_monitoring", "user_id")
    # ### end Alembic commands ###
