"""add user table

Revision ID: f578b64ec004
Revises: 4368be98316f
Create Date: 2024-11-05 15:49:03.176360

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from config.db.data_init import USER_DATA

# revision identifiers, used by Alembic.
revision: str = "f578b64ec004"
down_revision: Union[str, None] = "4368be98316f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user = op.create_table(
        "user",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("password", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=False),
        sa.Column("created_by", sa.String(length=40), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_by", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )

    op.bulk_insert(user, USER_DATA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
